# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:

  workflow_call:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: [e2-highcpu-32]

    env:
      CARGO_INCREMENTAL: 0
      # Compiler warnings should fail to compile
      EXTRA_CARGO_CONFIG: "target.'cfg(all())'.rustflags = [\"-Dwarnings\"]"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test commit name
        run: |
          echo "Build-Test: release_ref=$(git rev-parse HEAD)"

      - name: Check that Cargo.lock doesn't need to be updated
          # Note: this isn't the same as checking that Cargo.lock is up to date
          # (cargo update --locked), which makes sure that every package is the
          # latest published version. This is just ensuring that every
          # dependency has an entry in Cargo.lock that is compatible with the
          # version requirements in all Cargo.toml files.
        run: |
          # This works because cargo tree requires a Cargo.lock with no required updates
          cargo tree --locked > /dev/null || (
            echo "Please include required changes to Cargo.lock in your pull request"
            # Without the --locked flag, cargo will do the minimal possible update to Cargo.lock
            cargo tree > /dev/null 2> /dev/null
            # Print out the differences to ease debugging
            git diff Cargo.lock
            exit 1
          )

      - name: Check source-code formatting (run "cargo fmt" if this fails)
        run: |
          cargo fmt --check --all

      - name: Check license headers
        run: |
          cargo run -p caliptra-file-header-fix --locked -- --check

      - name: Build
        run: |
          cargo --config "$EXTRA_CARGO_CONFIG" build --locked
          drivers/test-fw/build.sh
          (cd fmc && ./build.sh)
          (cd runtime && ./build.sh)
          (cd rom/dev && ./build.sh)

      # Clippy needs to build crates as part of the check, so do it after the
      # build.
      - name: Clippy lint check
        run: |
          # Clippy doesn't look at --config, so manually set RUSTFLAGS to the
          # same as the build steps to avoid invalidating the cargo cache.
          RUSTFLAGS="-Dwarnings" cargo clippy --locked --all-targets -- -D warnings

      - name: Run tests
        run: |
          cargo --config "$EXTRA_CARGO_CONFIG" test --locked

      - name: Run emulator conformance tests
        run: |
          sudo apt-get install gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
          (cd /tmp/ && git clone --depth 1 --branch old-framework-2.x https://github.com/riscv-non-isa/riscv-arch-test)
          cargo --config "$EXTRA_CARGO_CONFIG" run --locked -p compliance-test -- --test_root_path /tmp/riscv-arch-test

      - name: ROM Makefile
        run: |
          (cd rom/dev && make run)

      - name: Caliptra HW-Model C Binding Smoke Test
        run: |
          git submodule update --init
          (cd hw-model/c-binding/examples && make run)

      - name: Caliptra C API Hwmodel Integration Test
        run: |
          (cd libcaliptra/examples/hwmodel && make && ./hwmodel)
